language: node_js

node_js: "10"

install:
  - npm install

jobs:
  include:
    - stage: unit tests with coverage
      script: yarn coverage
    - stage: run lint and build
      script: yarn run lint && yarn build
    - stage: npm release
      if: NOT type IN (pull_request)
      node_js: lts/*
      script:
        - npx semantic-release
      on: master
    - stage: deploy documentation
      if: branch IN (master) AND NOT type IN (pull_request)
      script:
        - git config --global user.name "${GH_NAME}"
        - git config --global user.email "${GH_EMAIL}"
        - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc
        - cd website && yarn install && GIT_USER="${GH_NAME}" yarn deploy
      on: master
